EndorsementRejection/Controllers/ApprovalUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EndorsementRejection.Data;
using EndorsementRejection.Models.Entities;

namespace EndorsementRejection.Controllers
{
    public class ApprovalUsersController : Controller
    {
        private readonly AppDbContext _context;

        public ApprovalUsersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: ApprovalUsers
        public async Task<IActionResult> Index()
        {
            return View(await _context.ApprovalUsers.ToListAsync());
        }

        // GET: ApprovalUsers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalUser = await _context.ApprovalUsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (approvalUser == null)
            {
                return NotFound();
            }

            return View(approvalUser);
        }

        // GET: ApprovalUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ApprovalUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,Password,Role")] ApprovalUser approvalUser)
        {

            if (ModelState.IsValid)
            {
                _context.Add(approvalUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(approvalUser);
        }

        // GET: ApprovalUsers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalUser = await _context.ApprovalUsers.FindAsync(id);
            if (approvalUser == null)
            {
                return NotFound();
            }
            return View(approvalUser);
        }

        // POST: ApprovalUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,Password,Role")] ApprovalUser approvalUser)
        {
            if (id != approvalUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(approvalUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApprovalUserExists(approvalUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(approvalUser);
        }

        // GET: ApprovalUsers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalUser = await _context.ApprovalUsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (approvalUser == null)
            {
                return NotFound();
            }

            return View(approvalUser);
        }

        // POST: ApprovalUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var approvalUser = await _context.ApprovalUsers.FindAsync(id);
            if (approvalUser != null)
            {
                _context.ApprovalUsers.Remove(approvalUser);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApprovalUserExists(int id)
        {
            return _context.ApprovalUsers.Any(e => e.Id == id);
        }
    }
}

EndorsementRejection/Controllers/EndoUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EndorsementRejection.Data;
using EndorsementRejection.Models.Entities;

namespace EndorsementRejection.Controllers
{
    public class EndoUsersController : Controller
    {
        private readonly AppDbContext _context;

        public EndoUsersController(AppDbContext context)
        {
            _context = context;
        }

        // GET: EndoUsers
        public async Task<IActionResult> Index()
        {
            return View(await _context.EndoUsers.ToListAsync());
        }

        // GET: EndoUsers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endoUser = await _context.EndoUsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (endoUser == null)
            {
                return NotFound();
            }

            return View(endoUser);
        }

        // GET: EndoUsers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EndoUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,Password,Role")] EndoUser endoUser)
        {
            if (ModelState.IsValid)
            {
                _context.Add(endoUser);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(endoUser);
        }

        // GET: EndoUsers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endoUser = await _context.EndoUsers.FindAsync(id);
            if (endoUser == null)
            {
                return NotFound();
            }
            return View(endoUser);
        }

        // POST: EndoUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserName,Password,Role")] EndoUser endoUser)
        {
            if (id != endoUser.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(endoUser);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EndoUserExists(endoUser.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(endoUser);
        }

        // GET: EndoUsers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endoUser = await _context.EndoUsers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (endoUser == null)
            {
                return NotFound();
            }

            return View(endoUser);
        }

        // POST: EndoUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var endoUser = await _context.EndoUsers.FindAsync(id);
            if (endoUser != null)
            {
                _context.EndoUsers.Remove(endoUser);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EndoUserExists(int id)
        {
            return _context.EndoUsers.Any(e => e.Id == id);
        }
    }
}

EndorsementRejection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EndorsementRejection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EndorsementRejection.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            @* <div class="container-fluid"> *@
            <div class="container align-content-center">


                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EndorsementRejection</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                Endo Rejections
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="EndoRejections" asp-action="Create">New Request</a>
                                <a class="dropdown-item" asp-controller="EndoRejections" asp-action="Index">Request List</a>
                                <a class="dropdown-item" asp-controller="EndoRejections" asp-action="ToBeApproved">To Be Approved</a>
                                <a class="dropdown-item" asp-controller="EndoRejections" asp-action="ToGenerateLetter">To Be Processed</a>
                                @*
                                <a class="dropdown-item" href="#"></a>
                                <a class="dropdown-item" href="#">Expired Contracts</a> *@
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                Setup
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="EndoUsers" asp-action="Index">Endo Users</a>
                                <a class="dropdown-item" asp-controller="ApprovalUsers" asp-action="Index">Approval Users</a>
                                @*
                                <a class="dropdown-item" href="#"></a>
                                <a class="dropdown-item" href="#">Expired Contracts</a> *@
                            </div>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EndorsementRejection - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>