EndorsementRejection/Models/Entities/EndoRejection.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EndorsementRejection.Models.Entities
{
    public class EndoRejection
    {
        [Key]
        [Required]
        public int Id { get; set; }

        [Required(ErrorMessage = "Requested By is Mandatory")]
        public string RequestedBy { get; set; }
        [Required(ErrorMessage = "Policy No is Mandatory")]
        public string PolicyNumber { get; set; }
        [Required(ErrorMessage = "Policy Holder is Mandatory")]
        public string PolicyHolder { get; set; }
        [Required(ErrorMessage = "Processed Type is Mandatory")]
        public string ProcessedType { get; set; }

        public string? EndoProcessed { get; set; }
        [Required(ErrorMessage = "Rejection Reason is Mandatory")]
        public string RejectionReason { get; set; }

        public string? ApprovalStatus { get; set; }
        public string? ApprovedBy { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime?  RequestedDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime? ApprovedDate { get; set; }
        public string? ApprovalComments { get; set; }
        public string? completedBy { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.Date)]
        public DateTime? completedDate { get; set; }
        public string? RejectionLetterComments { get; set; }

        public EndoRejection()
        {
            RequestedDate = DateTime.Now;
            //ApprovedDate = DateTime.Now;
        }

        [NotMapped]
        public string? ReferralUrl { get; set; }




    }
}

EndorsementRejection/Controllers/EndoRejectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EndorsementRejection.Data;
using EndorsementRejection.Models.Entities;
using EndorsementRejection.Infrastructure.Abstract;
using EndorsementRejection.Infrastructure.Repository;

namespace EndorsementRejection.Controllers
{
    public class EndoRejectionsController : Controller
    {
        private readonly AppDbContext _context;

        public EndoRejectionsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: EndoRejectionsToBeApproved
        public async Task<IActionResult> ToBeApproved()
        {
            return View(await _context.EndoRejections.Where(Rejection => Rejection.ApprovalStatus == null).ToListAsync());
        }

        // GET: EndoRejectionsToGenerateLetter
        public async Task<IActionResult> ToGenerateLetter()
        {
            IUserRepository EndoUserRepo = new UserRepository(_context);
            List<EndoUser> EndoUserList = EndoUserRepo.EndoUserList();
            //List<ApprovalUser> ApprovalUserList = EndoUserRepo.ApprovalUserList();
            ViewBag.EndoUserList = EndoUserList;
            //ViewBag.ApprovalUserList = ApprovalUserList;
            return View(await _context.EndoRejections.Where(Rejection => Rejection.completedBy == null && Rejection.ApprovedBy != null).ToListAsync());
        }


        // POST: EndoRejectionsToGenerateLetter
        [HttpPost]
        public async Task<IActionResult> ToGenerateLetter(string Search, string Clear, string User, string AllRecords)
        {
            List<EndoRejection> ListPolicy = new List<EndoRejection>();

            IUserRepository EndoUserRepo = new UserRepository(_context);
            List<EndoUser> EndoUserList = EndoUserRepo.EndoUserList();
            //List<ApprovalUser> ApprovalUserList = EndoUserRepo.ApprovalUserList();
            ViewBag.EndoUserList = EndoUserList;
            //ViewBag.ApprovalUserList = ApprovalUserList;

            if (!string.IsNullOrEmpty(Clear))
            {
                return RedirectToAction("ToGenerateLetter");
            }


            if (!string.IsNullOrEmpty(Search))
            {
                try
                {



                    if (User != "")
                    {

                        //ViewBag.TableName = formcollection["PolicyNoSearch"];
                        ViewBag.User = User;
                        //HttpCookie RT = new HttpCookie("ResultTableName", formcollection["ResultTableName"]);
                        //HttpContext.Response.AppendCookie(new HttpCookie("PolicyNo", PolicyNo));

                        if (AllRecords == "AllRecords")
                        {
                            //return View(await _context.EndoRejections.Where(Rejection => Rejection.completedBy == null && Rejection.ApprovedBy != null).ToListAsync());
                            ListPolicy = await _context.EndoRejections.Where(Rejection => Rejection.RequestedBy == User).OrderByDescending(c => c.Id).ThenBy(n => n.ApprovalStatus).ToListAsync();

                        }
                        else
                        {
                            //List<EndoRejection> ListPolicy = await _context.EndoRejections.Where(EndoRejection => EndoRejection.RequestedBy == User).OrderByDescending(c => c.ApprovedDate).ThenBy(n => n.ApprovalStatus).ToListAsync();
                            ListPolicy = await _context.EndoRejections.Where(Rejection => Rejection.completedBy == null && Rejection.ApprovedBy != null && Rejection.RequestedBy == User).OrderByDescending(c => c.ApprovedDate).ThenBy(n => n.ApprovalStatus).ToListAsync();
                        }
                        if (ListPolicy.Count() == 0)
                        {

                            TempData["Message"] = "No Records Found";
                            return View(ListPolicy);
                            //return RedirectToAction("Index");
                            //return RedirectToAction("GetPolicy", new { PolicyNoSearch = PolicyNoSearch });

                        }
                        else
                        {
                            //ViewBag.EnableAddRow = true;

                            return View(ListPolicy);
                        }

                    }

                    //Export(ListVendorName);










                }

                catch (Exception ex)
                {

                    return RedirectToAction("Index");
                }
            }

            return View(await _context.EndoRejections.Where(Rejection => Rejection.completedBy == null && Rejection.ApprovedBy != null).ToListAsync());
        }

        // GET: EndoRejections
        public async Task<IActionResult> Index()
        {
            return View(await _context.EndoRejections.OrderByDescending(Req => Req.Id).Take(100).ToListAsync());
        }


        // POST: EndoRejections
        [HttpPost]
        public async Task<IActionResult> Index(string Search, string PolicyNo, string Clear)
        {
            if (!string.IsNullOrEmpty(Clear))
            {
                return RedirectToAction("Index");
            }


            if (!string.IsNullOrEmpty(Search))
            {
                try
                {



                    if (PolicyNo != "")
                    {

                        //ViewBag.TableName = formcollection["PolicyNoSearch"];
                        ViewBag.PolicyNo = PolicyNo;
                        //HttpCookie RT = new HttpCookie("ResultTableName", formcollection["ResultTableName"]);
                        //HttpContext.Response.AppendCookie(new HttpCookie("PolicyNo", PolicyNo));


                        List<EndoRejection> ListPolicy = await _context.EndoRejections.Where(EndoRejection => EndoRejection.PolicyNumber == PolicyNo).ToListAsync();


                        if (ListPolicy.Count() == 0)
                        {

                            TempData["Message"] = "No Records Found";
                            return View(ListPolicy);
                            //return RedirectToAction("Index");
                            //return RedirectToAction("GetPolicy", new { PolicyNoSearch = PolicyNoSearch });

                        }
                        else
                        {
                            //ViewBag.EnableAddRow = true;

                            return View(ListPolicy);
                        }

                    }

                    //Export(ListVendorName);










                }

                catch (Exception ex)
                {

                    return RedirectToAction("Index");
                }
            }

            return View(await _context.EndoRejections.ToListAsync());
        }

        // GET: EndoRejections/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var endoRejection = await _context.EndoRejections
                .FirstOrDefaultAsync(m => m.Id == id);
            if (endoRejection == null)
            {
                return NotFound();
            }

            return View(endoRejection);
        }

        // GET: EndoRejections/Create
        public IActionResult Create()
        {
            EndoRejection endorejectionViewModel = new EndoRejection();
            IUserRepository EndoUserRepo = new UserRepository(_context);
            List<EndoUser> EndoUserList = EndoUserRepo.EndoUserList();
            List<ApprovalUser> ApprovalUserList = EndoUserRepo.ApprovalUserList();
            ViewBag.EndoUserList = EndoUserList;
            ViewBag.ApprovalUserList = ApprovalUserList;
            return View(endorejectionViewModel);
        }

        // POST: EndoRejections/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RequestedBy,PolicyNumber,PolicyHolder,ProcessedType,EndoProcessed,RejectionReason,ApprovalStatus,ApprovedBy,RequestedDate,ApprovedDate,ApprovalComments,completedBy,completedDate,RejectionLetterComments,ReferralUrl")] EndoRejection endoRejection)
        {
            string ReturnUrl = Request.Headers["Referer"].ToString();

            ViewBag.ReturnUrl = "Index";
            endoRejection.ReferralUrl = "Index";


            EndoRejection endorejectionViewModel = new EndoRejection();
            IUserRepository EndoUserRepo = new UserRepository(_context);
            List<EndoUser> EndoUserList = EndoUserRepo.EndoUserList();
            List<ApprovalUser> ApprovalUserList = EndoUserRepo.ApprovalUserList();
            ViewBag.EndoUserList = EndoUserList;
            ViewBag.ApprovalUserList = ApprovalUserList;

            if (endoRejection.RequestedBy == "Select")
            {
                endoRejection.RequestedBy = null;
                // ViewBag.RequestedBy = "Requested By field is required";
                ModelState.AddModelError(nameof(EndoRejection.RequestedBy), "Requested By is required");
            }
            if (endoRejection.ProcessedType == "Partial")
            {
                if (endoRejection.EndoProcessed == null || endoRejection.EndoProcessed == "")
                {
                    ModelState.AddModelError(nameof(EndoRejection.EndoProcessed), "Endo processed for partial rejection is required");

                }
            }
            if (endoRejection.completedBy == "Select")
            {
                endoRejection.completedBy = null;

            }

            if (ModelState.IsValid)
            {
                _context.Add(endoRejection);

EndorsementRejection/Views/EndoRejections/Delete.cshtml
@model EndorsementRejection.Models.Entities.EndoRejection

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EndoRejection</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequestedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyHolder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyHolder)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProcessedType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProcessedType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RejectionReason)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RejectionReason)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApprovalStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApprovedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RequestedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RequestedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApprovedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalComments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApprovalComments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.completedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.completedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.completedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.completedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EndorsementRejection/Views/EndoRejections/Index.cshtml
@model IEnumerable<EndorsementRejection.Models.Entities.EndoRejection>

@{
    ViewData["Title"] = "Index";
}

@* <h1>Index</h1> *@
<h4 class="text-center">Request List</h4>

@* <h5>Search By PolicyNo</h5> *@
<p>
    @using (Html.BeginForm("Index", "EndoRejections", FormMethod.Post))
    {
        @*@Html.ActionLink("Create New Vendor", "Create")*@
        <div> @TempData["Message"]</div>
        <div>

            <b> PolicyNo: </b>
            @Html.TextBox("PolicyNo", (object)ViewBag.PolicyNo)

            <input type="submit" id="Search" value="Search" name="Search" />
            <input type="submit" id="btnClear" value="Clear" name="Clear" />
            <a asp-action="Create" style="float: right;">Create New</a>
        </div>
    }
</p>
@* <div style="float: right;">
    <p>
        <a asp-action="Create" style="float: right;">Create New</a>
    </p>
</div> *@

<div class="datatable-container">

    <table class="table table-sm table-responsive table-striped table-bordered table-hover zero-configuration" id="tbllist">

       @* <table class="table"> *@
        <thead class="table-dark">
            <tr>
                <th class="text-center  text-wrap">
                    @Html.DisplayNameFor(model => model.Id)

                </th>
                <th class="text-center  text-wrap">
                    @Html.Label("Requested By")
                </th>
                <th>
                    @Html.Label("Policy No")
                </th>
                <th class="text-center  text-wrap">

                    @Html.Label("Policy Holder")
                   
                </th>
                <th class="text-center  text-wrap">

                    @Html.Label("Req Date")

                    @* @Html.DisplayNameFor(model => model.RequestedDate) *@
                </th>
                <th class="text-center  text-wrap">

                    @Html.Label("Processed Type")

                    @* @Html.DisplayNameFor(model => model.ProcessedType) *@
                </th>
                <th class="text-center  text-wrap">

                    @Html.Label("Approval Status")

                    @* @Html.DisplayNameFor(model => model.ApprovalStatus) *@
                </th>
                <th class="text-center  text-wrap">

                    @Html.Label("Approved By")

                    @* @Html.DisplayNameFor(model => model.ApprovedBy) *@
                </th>

                <th class="text-center  text-wrap">

                    @Html.Label("Approved Date")

                    @* @Html.DisplayNameFor(model => model.ApprovedDate) *@
                </th>
                @* <th>
                    @Html.Label("Approval Comments")

                    @* @Html.DisplayNameFor(model => model.ApprovalComments) 
                </th> *@
                <th class="text-center  text-wrap">

                    @Html.Label("Completed By")

                    @* @Html.DisplayNameFor(model => model.completedBy) *@
                </th>
                <th class="text-center  text-wrap">

                    @Html.Label("Completed Date")

                    @* @Html.DisplayNameFor(model => model.completedDate) *@
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RequestedBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PolicyNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PolicyHolder)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RequestedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProcessedType)
                    </td>
@*                     <td>
                        @Html.DisplayFor(modelItem => item.RejectionReason)
                    </td> *@
                    <td>
                        @Html.DisplayFor(modelItem => item.ApprovalStatus)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApprovedBy)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.ApprovedDate)
                    </td>
@*                     <td>
                        @Html.DisplayFor(modelItem => item.ApprovalComments)
                    </td> *@
                    <td>
                        @Html.DisplayFor(modelItem => item.completedBy)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.completedDate)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> @* |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<!-- Path: EndorsementRejection/Views/EndoRejections/Index.cshtml -->
<!-- Compare this snippet from EndorsementRejection/Views/Shared/_Layout.cshtml: -->
<!-- <!DOCTYPE html>
 -->
<!-- <html lang="en">
-->
<!-- <head>
-->
<!--     <meta charset="utf-8" />
-->
<!--     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
-->
<!--     <title>@ViewData["Title"] - EndorsementRejection</title>
-->
<!--     <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
-->
<!--     <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
-->
<!--     <link rel="stylesheet" href="~/EndorsementRejection.styles.css" asp-append-version="true" />
--> 
<!-- </head>

-->
<!-- <body>
--> 
<!--     <header>   
--> 
<!--         <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> 
--> 
<!--             <div class="container-fluid">  
--> 
        <!--                 <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EndorsementRejection</a>
-->
        <!--                 <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"    
-->
        <!--                         aria-expanded="false" aria-label="Toggle navigation">  
--> 
        <!--                     <span class="navbar-toggler-icon"></span>
--> 
        <!--                 </button>
                -->
                    <!--                 <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            -->
<!--                     <ul class="navbar-nav flex-grow-1">
--> 
<!--                         <li class="nav-item">
--> 
<!--                             <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
--> 
<!--                         </li>
-->
<!--                         <li class="nav-item">
-->

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<style type="text/css">
    #tbllist_filter {
        margin-bottom: 1%;
    }
</style>
<script type="text/javascript">
    var js = jQuery.noConflict(true);
    js(document).ready(function () {
        js('#tbllist').DataTable({
            order: [[0, 'des']]
        });
        // LoadListing();
    });
</script>

EndorsementRejection/Views/EndoRejections/ToGenerateLetter.cshtml
@model IEnumerable<EndorsementRejection.Models.Entities.EndoRejection>

@{
    ViewData["Title"] = "ToGenerateLetter";
}

@* <h1>ToGenerateLetter</h1> *@
<h4 class="text-center">To Be Processed</h4>

@* <h5>Search By PolicyNo</h5> *@
<p>
    @using (Html.BeginForm("ToGenerateLetter", "EndoRejections", FormMethod.Post))
    {
        @*@Html.ActionLink("Create New Vendor", "Create")*@
        <div> @TempData["Message"]</div>
        <div>

            @* <b> Requested By: </b> *@
            <select id="User" value="User" name="User" asp-items="@(new SelectList(ViewBag.EndoUserList,"UserName", "UserName"))" class="form-select-sm">
                <option value="" selected disabled>---Select Requested By---</option>
            </select>
            @* @Html.DropDownList(new SelectList(ViewBag.EndoUserList, "UserName", "UserName")er)
        <select asp-for="RequestedBy"
        class="form-select"
        asp-items="@(new SelectList(ViewBag.EndoUserList,"UserName", "UserName"))">
        </select>
        *@
            <input type="submit" id="Search" value="Search" name="Search" />
            <input type="submit" id="btnClear" value="Clear" name="Clear" />


        </div>
        <div>
            All Records:
            <input id="AllRecords" value="AllRecords" name="AllRecords" type="checkbox" checked="@(1 == 0)">
        </div>
    }
</p>
<p>
    @* <a asp-action="Create">Create New</a> *@
</p>
<table class="table table-sm table-responsive table-striped table-bordered table-hover zero-configuration" id="tbllist">

    <thead class="table-dark">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>

            <th class="text-center  text-wrap">
                @Html.Label("Requested By")
            </th>
            <th class="text-center  text-wrap">

                @Html.Label("Policy No")
            </th>
            <th class="text-center  text-wrap">

                @Html.Label("Policy Holder")

            </th>
            <th class="text-center  text-wrap">

                @Html.Label("Req Date")

                @* @Html.DisplayNameFor(model => model.RequestedDate) *@
            </th>
            <th class="text-center  text-wrap">

                @Html.Label("Processed Type")

                @* @Html.DisplayNameFor(model => model.ProcessedType) *@
            </th>
            <th class="text-center  text-wrap">

                @Html.Label("Approval Status")

                @* @Html.DisplayNameFor(model => model.ApprovalStatus) *@
            </th>
            <th class="text-center  text-wrap">

                @Html.Label("Approved By")

                @* @Html.DisplayNameFor(model => model.ApprovedBy) *@
            </th>

            <th class="text-center  text-wrap">

                @Html.Label("Approved Date")

                @* @Html.DisplayNameFor(model => model.ApprovedDate) *@
            </th>
            @* <th>
            @Html.Label("Approval Comments")

            @* @Html.DisplayNameFor(model => model.ApprovalComments)
            </th> *@
            <th class="text-center  text-wrap">

                @Html.Label("Completed By")

                @* @Html.DisplayNameFor(model => model.completedBy) *@
            </th>
            <th class="text-center  text-wrap">

                @Html.Label("Completed Date")

                @* @Html.DisplayNameFor(model => model.completedDate) *@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PolicyNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PolicyHolder)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProcessedType)
                </td>
                @*                     <td>
            @Html.DisplayFor(modelItem => item.RejectionReason)
            </td> *@
                <td>
                    @Html.DisplayFor(modelItem => item.ApprovalStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApprovedBy)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.ApprovedDate)
                </td>
                @*                     <td>
            @Html.DisplayFor(modelItem => item.ApprovalComments)
            </td> *@
                <td>
                    @Html.DisplayFor(modelItem => item.completedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.completedDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> @* |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
                </td>
            </tr>
        }
    </tbody>
</table>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<style type="text/css">
    #tbllist_filter {
        margin-bottom: 1%;
    }
</style>
<script type="text/javascript">
    var js = jQuery.noConflict(true);
    js(document).ready(function () {
        js('#tbllist').DataTable({
            order: [[0, 'asc']]
        });
        // LoadListing();
    });
</script>